spring:
  application:
    name: byakugan-kensaku
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5-coder:7b
github:
  apiToken: ${GH_API_TOKEN}
  webhookSecret: ${GH_WEBHOOK_SECRET}