spring:
  application:
    name: byakugan-kensaku
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5-coder:1.5b
github:
  api:
   token: ${GH_API_TOKEN}
  webhook:
    secret: ${GH_WEBHOOK_SECRET}